### ISSUE TITLE
Using strings as .source considered harmful 🙂

### ISSUE THREAD

**Issue by rycee** [JonathanReeve/dotfiles#1]
Hi, came here from the reddit thread and noticed you in some cases are using strings as file `source`. For example

https://github.com/JonathanReeve/dotfiles/blob/77e45eb1b0fbdbb74d9c8511d9034e7afd4d0e2b/dotfiles/home.nix#L358-L360

This may not be what you want, in most cases you'd want this to be a Nix path literal since only then will the file be copied to the Nix store and immutability maintained. Right now, if you run, for example,
```console
$ readlink ~/.config/sxhkd/sxhkdrc
```
I suspect you'll find that it is a symbolic link to the file within your Git repo. So editing the file in the repo will change the "live" configuration as well.

If instead you change the code line to read

    "sxhkd/sxhkdrc".source = ./sxhkdrc;

and rerun the `readlink` command it should show a file within the Nix store and this file's content will be immutable.

**Comment by JonathanReeve** [comment]
Thanks for this! I didn't know about that way to specify paths. I just fixed this above.
